<div class="page-header clearfix">
    <h2>New Customer</h2>
</div>
<form role="form" action="" method="post">
    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" class="form-control" name="name" id="name"
                placeholder="Enter Name">
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="text" class="form-control" name="email" id="email"
                placeholder="Enter Email">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>