<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand text-white" href="/">CleanPhp</a>
        <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link text-warning" href="/customers">Customers</a>
                <a class="nav-link text-warning" href="/orders">Orders</a>
                <a class="nav-link text-warning" href="/invoices">Invoices</a>
            </div>
        </div>
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
            <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
            <button type="button" class="btn btn-outline-light me-2">Login</button>
            <button type="button" class="btn btn-warning">Sign-up</button>
        </div>
    </div>
</nav>
<!--<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start bg-dark">-->
<!--    -->
<!--</div>-->
<!---->
<!--<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start bg-dark">-->
<!--    <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">-->
<!--        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">-->
<!--            <use xlink:href="#bootstrap"></use>-->
<!--        </svg>-->
<!--    </a>-->
<!---->
<!--    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">-->
<!--        <li><a href="#" class="nav-link px-2 text-warning">Features</a></li>-->
<!--        <li><a href="#" class="nav-link px-2 text-warning">Pricing</a></li>-->
<!--        <li><a href="#" class="nav-link px-2 text-warning">FAQs</a></li>-->
<!--        <li><a href="#" class="nav-link px-2 text-warning">About</a></li>-->
<!--    </ul>-->
<!---->
<!--    <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">-->
<!--        <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">-->
<!--    </form>-->
<!---->
<!--    <div class="text-end">-->
<!--        <button type="button" class="btn btn-outline-light me-2">Login</button>-->
<!--        <button type="button" class="btn btn-warning">Sign-up</button>-->
<!--    </div>-->
<!--</div>-->